title: Blog of Tim
url: https://www.tim-schiemann.de
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: "dark"
repository: tmace85/tmace85.github.io
plugins:
- jekyll-remote-theme
- jekyll-include-cache
include: ["_pages"]

defaults:
  # posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true

name                     : &name "Tim" # &name is a YAML anchor which can be *referenced later
description              : &description "Seite über mich"
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/tim_xletix.jpg"
  bio              : "Nerd"
  location         : "Berlin"
  links:
    - label: "bemodi - IT Dienstleister"
      icon: "fab fa-fw fa-bemodi-square"
      url: "https://www.bemodi.de/"
    - label: "LinkedIN"
      icon: "fab fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/tschiemann"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tmace85"
    - label: "BlueSky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/tim-schiemann.de"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://berlin.social/@mtdon"
    - label: "Geekparents Podcast"
      icon: "fab fa-fw fa-mastodon"
      url: "https://www.geekparents.de"



footer:
  links:
    - label: "bemodi - unabhängiger IT Dienstleister"
      icon: "fab fa-fw fa-bemodi-square"
      url: "https://www.bemodi.de/"
    - label: "LinkedIN"
      icon: "fab fa-fw fa-linkedin-square"
      url: "https://www.linkedin.com/in/tschiemann"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/tmace85"
    - label: "BlueSky"
      icon: "fab fa-fw fa-bluesky"
      url: "https://bsky.app/profile/tim-schiemann.de"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://berlin.social/@mtdon"
    - label: "Geekparents Podcast"
      icon: "fab fa-fw fa-mastodon"
      url: "https://www.geekparents.de"
    - label: "PayPal Kaffeespende"
      url: https://paypal.me/TimRohde?country.x=DE&locale.x=de_DE
